/**
 * iJento Tags 14.0.42
 * Copyright (C) 2014 iJento LTD
 * cad1eef9fa35874e3d19b88652e8a29503b6bca9
 */
(function(q){function v(a){this._input=a;this._index=-1;this._buffer=[]}var A=/^\s*[^@^\s]{1,255}@[^@^\s]{1,255}\s*$/,B=function(a){var b=[],c=0;this.append=function(a){b[b.length]=a;c+=a.length;return this};this.toString=function(){return b.join("")};this.length=function(){return c};a&&this.append(a)},d=function(){};d.isHTMLform=function(a){return null===a?!1:"object"===typeof a?null!=={}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].match(/htmlformelement/i):!1};d.isArray=function(a){return null===
a?!1:"object"===typeof a?null!==a.constructor.toString().match(/array/i)||void 0!==a.length:!1};d.isString=function(a){return null===a?!1:"string"===typeof a?!0:"object"===typeof a?null!==a.constructor.toString().match(/string/i):!1};d.isBoolean=function(a){return null===a?!1:"boolean"===typeof a?!0:"object"===typeof a?null!==a.constructor.toString().match(/boolean/i):!1};d.isFunction=function(a){return null===a?!1:"function"===typeof a?null!==a.constructor.toString().match(/Function/):!1};d.isObject=
function(a){return null===a?!1:"object"===typeof a?null!==a.constructor.toString().match(/object/i):!1};var s,n,r,w,p;d.quote=function(a){s.lastIndex=0;return s.test(a)?'"'+a.replace(s,function(a){var c=w[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'};d.str=function(a,b){var c,e,d,l,f=n,g,k=b[a];k&&"object"===typeof k&&"function"===typeof k.toJSON&&(k=k.toJSON(a));"function"===typeof p&&(k=p.call(b,a,k));switch(typeof k){case "string":return this.quote(k);
case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";n+=r;g=[];if("[object Array]"===Object.prototype.toString.apply(k)){l=k.length;for(c=0;c<l;c+=1)g[c]=this.str(c,k)||"null";d=0===g.length?"[]":n?"[\n"+n+g.join(",\n"+n)+"\n"+f+"]":"["+g.join(",")+"]";n=f;return d}if(p&&"object"===typeof p)for(l=p.length,c=0;c<l;c+=1)"string"===typeof p[c]&&(e=p[c],(d=this.str(e,k))&&g.push(this.quote(e)+(n?": ":":")+d));else for(e in k)Object.prototype.hasOwnProperty.call(k,
e)&&(d=this.str(e,k))&&g.push(this.quote(e)+(n?": ":":")+d);d=0===g.length?"{}":n?"{\n"+n+g.join(",\n"+n)+"\n"+f+"}":"{"+g.join(",")+"}";n=f;return d}};d.shiftArgs=function(a){var b=[];a&&(b=Array.prototype.slice.call(a),b.shift());return b};d.getCallBack=function(a){var b=null;if(a)for(var c=0;c<a.length;c++)this.isFunction(a[c])&&(b=a[c]);return b};d.getFieldObject=function(a){var b={};if(a)for(var c=0;c<a.length;c++)null!==a[c]&&this.isObject(a[c])&&(b=a[c]);return b};d.getArgParams=function(a){var b=
[];if(a)for(var c=0;c<a.length;c++)null!==a[c]&&this.isObject(a[c])||this.isFunction(a[c])||b.push(a[c]);return b};d.getFieldValueByPrefix=function(a,b,c){for(var d in b)d.match(new RegExp("^"+a+"([A-Za-z0-9]*)$"))&&(c[d]=b[d]);return c};d.isEmpty=function(a){return null===a||void 0===a?!0:"string"==typeof a&&0===a.trim().length?!0:!1};d.isEmptyObject=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};d.doScrollCheck=function(){var a=document.documentElement,b=document.body;return(a&&
a.scrollLeft||b&&b.scrollLeft||0)+"x"+(a&&a.scrollTop||b&&b.scrollTop||0)};d.getCollectionServer=function(a){var b=null;this.isString(a)&&a.match(A)&&(a=a.split("@"),b="//"+a[1]+"/"+a[0]+"/track.gif");return b};d.splitActionStr=function(a){var b=[];if(0<a.indexOf(".")){var c=a.split(".");0<c[1].indexOf(":")?(a=c[1].split(":"),b.tracker=c[0],b.module=a[0],b["function"]=a[1]):(b.tracker=c[0],b["function"]=c[1])}else 0<a.indexOf(":")?(a=a.split(":"),b.tracker=f.getDefaultTrackerName(),b.module=a[0],
b["function"]=a[1]):(b.tracker=f.getDefaultTrackerName(),b["function"]=a);return b};d.TRANS_CHARS="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/_";d.encodeString=function(a){var b=new B;for(a=new v(a);a.moveNext();){var c=a.current;a.moveNext();var e=a.current;a.moveNext();var h=a.current,l=c>>2,c=(c&3)<<4|e>>4,f=(e&15)<<2|h>>6,g=h&63;isNaN(e)?f=g=64:isNaN(h)&&(g=64);b.append(d.TRANS_CHARS.charAt(l)+d.TRANS_CHARS.charAt(c)+d.TRANS_CHARS.charAt(f)+d.TRANS_CHARS.charAt(g))}return b.toString()};
v.prototype={current:Number.NaN,moveNext:function(){if(0<this._buffer.length)return this.current=this._buffer.shift(),!0;if(this._index>=this._input.length-1)return this.current=Number.NaN,!1;var a=this._input.charCodeAt(++this._index);13==a&&10==this._input.charCodeAt(this._index+1)&&(a=10,this._index+=2);128>a?this.current=a:(127<a&&2048>a?this.current=a>>6|192:(this.current=a>>12|224,this._buffer.push(a>>6&63|128)),this._buffer.push(a&63|128));return!0}};d.hash=function(a){if(null===a)return"";
for(var b=2166136261,c=0;c<a.length;c++)b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24),b^=a.charCodeAt(c);return Number(b&4294967295).toString(16)};d.generateChecksum=function(a){for(var b=1,c=0,d=0;d<a.length;d++)b+=a.charCodeAt(d),c+=b;return(c%65521*65536+b%65521).toString(16)};d.setCookie=function(a,b,c,d){var h={};try{a&&b&&(c=c?c:0,h.cookieDetails=null,h.cookieType="n",this.deleteCookie(a),0<c&&(h.cookieDetails=d?this.setCookieWithDomain(a,b,d,c):this.setCookieNoDomain(a,b,c),h.cookieDetails?h.cookieType=
"p":c=0),"n"==h.cookieType&&0>=c&&(h.cookieDetails=d?this.setCookieWithDomain(a,b,d,c):this.setCookieNoDomain(a,b,c),h.cookieDetails&&(h.cookieType="s")))}catch(l){}return h};d.getCookie=function(a){return this.extractPart(a,document.cookie,";")};d.deleteCookie=function(a,b){b?this.setCookieWithDomain(a,"null",b,-1):this.setCookieNoDomain(a,"null",-1)};d.buildCookieText=function(a,b,c,d,h){var l=null;a&&b&&(l=a+"="+b,c&&(l=l+"; path="+c),d&&(l=l+"; domain="+d),h&&(0<h?(a=new Date,a.setTime(a.getTime()+
h),l=l+"; expires="+a.toGMTString()):0>h&&(l+="; expires=Thu, 1 Jan 1970 00:00:00 GMT")));return l};d.setCookieWithDomain=function(a,b,c,d){c=this.buildCookieText(a,b,"/",c,d);document.cookie=c;return this.getCookie(a)==b?c:null};d.setCookieNoDomain=function(a,b,c){for(var d=null,h=document.location.hostname.split("."),l="",f=h.length-1;0<=f&&!d;f--)l=(0!==f?".":"")+h[f]+l,d=this.setCookieWithDomain(a,b,l,c);return d};d.extractPart=function(a,b,c){var d=a+"=",h=null,l=b.indexOf(d);-1!=l&&0<a.length&&
(a=b.indexOf(c,l),-1==a&&(a=b.length),h=b.substring(l+d.length,a));return h};d.getPageVisibilityAttributeName=function(){var a="";"undefined"!==typeof document.visibilityState?a="visibilityState":"undefined"!==typeof document.mozVisibilityState?a="mozVisibilityState":"undefined"!==typeof document.msVisibilityState?a="msVisibilityState":"undefined"!==typeof document.webkitVisibilityState&&(a="webkitVisibilityState");return a};d.getPageVisibilityState=function(){var a=this.getPageVisibilityAttributeName();
return""!==a?document[a]:""};var C=function(){if("prerender"!=d.getPageVisibilityState())for(var a=ijDispatcher.tagSets,b=0;b<a.length;b++)a[b]&&a[b].isPreRendering&&(a[b].isPrivacyBlocked?a[b].isPreRendering=!1:(a[b].isPreRendering=!1,"deferred"==a[b].hit.sendMethod?ijDispatcher.deferTagSet(a[b],!0):"immediate"==a[b].hit.sendMethod&&ijDispatcher.dispatchTagSet(a[b],!0)));for(a=0;a<f.trackerArray.length;a++)f.trackerArray[a]&&"onchange"==f.trackerArray[a].fields.visibilityStateMonitor&&0<f.trackerArray[a].hits&&
f.trackerArray[a].send("event",{eventCategory:"Page Visibility",eventAction:d.getPageVisibilityState(),eventLabel:"Page visibility changed to "+d.getPageVisibilityState(),nonInteraction:!0})};d.bindVisibilityStateChanger=function(){var a="";"undefined"!==typeof document.hidden?a="visibilitychange":"undefined"!==typeof document.mozHidden?a="mozvisibilitychange":"undefined"!==typeof document.msHidden?a="msvisibilitychange":"undefined"!==typeof document.webkitHidden&&(a="webkitvisibilitychange");""!==
a&&document.addEventListener&&document.addEventListener(a,C,!1)};d.mergeObjects=function(a,b){for(var c in b)a[c]=b[c];return a};d.addListener=function(a,b,c){"object"==typeof a&&"string"==typeof b&&"function"==typeof c&&(a.addEventListener?a.addEventListener(b,c):a.attachEvent&&a.attachEvent("on"+b,c))};d.runCallback=function(a,b){try{this.isFunction(a)&&a.call(null,b)}catch(c){}};d.makeClientId=function(){return window.history.length+"."+Math.round(2147483647*Math.random())+"."+(new Date).getTime()+
"."+this.hash(document.location.href+document.referrer+navigator.userAgent)};d.contentList="page title hostname pageId pageChannel pageType pageHierarchy pageVersion pageVariant pageAuthor pageDimensions screenName".split(" ");d.eventList="eventCategory eventAction eventLabel eventValue eventCatId eventCatLabel eventItemId eventItemType eventItemLabel eventText nonInteraction linkid".split(" ");d.customFieldList=["dimension","metric","variable"];d.appFieldList=["appName","appId","appVersion","appInstallerId"];
d.clientDataList=["tz","language","encoding","screenColors"];d.campaignDataList="campaignSource campaignMedium campaignName campaignKeyword campaignContent campaignGclid campaignId".split(" ");d.campaignParamList="utm_source utm_medium utm_campaign utm_term utm_content gclid".split(" ");d.exceptionDataList=["exDescription","exFatal","exCategory","exCode"];d.timingDataList=["timingCategory","timingVar","timingValue","timingLabel"];d.socialDataList=["socialNetwork","socialAction","socialTarget"];d.contentExperimentDataList=
["expId","expVar"];var x=function(a,b){this.hitType=a;this.tracker=null;this.v="14.0";this.id=(new Date).getTime()+"."+Math.round(2147483647*Math.random())+(b?"."+d.hash(b.fields.clientId):"");this.hitParts=[];this.hitCallback=null;this.sendMethod="immediate"};x.prototype.addPart=function(a){a&&a.hasData()&&this.hitParts.push(a)};var t=function(){this.d=this.f=""};t.prototype.addToken=function(a,b,c){var e=null;c=Math.floor(.67*(c-this.f.length-this.d.length));0>=c?e=b:(c<b.length&&(e=b.substring(c),
b=b.substring(0,c)),this.f+=a,this.d=this.d+d.encodeString(b)+"*");return e};t.prototype.hasData=function(){return 0<this.f.length&&0<this.d.length?!0:!1};var y=function(a){this.tagIds=[];this.urls=[];this.images=[];this.imagesComplete=0;this.cookie=null;this.didTimeOut=this.doneCallback=this.isComplete=this.isRequested=this.isDeferred=!1;this.hit=a},f=function(){try{if(0<arguments.length)if(d.isFunction(arguments[0]))try{arguments[0].call(null,f.getDefaultTracker())}catch(a){}else if(d.isString(arguments[0])){var b=
d.splitActionStr(arguments[0]),c=b["function"],e=b.tracker,h=b.module;if(c){var l=d.shiftArgs(arguments);if("create"==c)f.create.apply(f,l);else if(0<f.trackerArray.length){var g=f.trackerMap[e];if(g)if(!h)d.isFunction(g[c])&&g[c].apply(g,l);else if(h&&g.modules[h]){var m=g.modules[h];Array.isArray(m)?m.push(arguments):d.isFunction(m[c])&&m[c].apply(m,l)}}}}}catch(k){}};f.trackerArray=[];f.trackerMap={};f.moduleMap={};f.getDefaultTracker=function(){return f.trackerMap.t0?f.trackerMap.t0:0<f.trackerArray.length?
f.trackerArray[0]:null};f.getDefaultTrackerName=function(){var a=f.getDefaultTracker();return a?a.fields.name:"t0"};f.create=function(){var a=null;if(0<arguments.length){var b=new g;b.initialise();if(b.setField("datamartId",arguments[0])){var c=!0,e=d.getCallBack(arguments),h=d.getFieldObject(arguments);if(h)for(var l in h)if(c=b.setField(l,h[l]),!c)break;c&&(b.fields.name||(c=b.setField("name","t0")));c&&(c=b.fields.name,a=b,this.trackerArray.push(a),this.trackerMap[c]=a,a.setClientId(),a.setCampaignData());
d.runCallback(e,a)}}return a};f.getAll=function(){return f.trackerArray};f.getByName=function(a){return d.isString(a)||null===a?(a=(a=d.isString(a)?a.trim():a)?f.trackerMap[a]:f.getDefaultTracker())?a:null:null};f.getQP=function(a){return d.extractPart(a,decodeURIComponent(document.URL.replace(/\+/g," ")),"&")};f.getTagSets=function(){return ijDispatcher.tagSets};f.getUtilities=function(){return d};var g=function(){this.fields={};this.modules={};this.pageHitsSent=this.hits=0;this.documentId=null};
g.prototype.initialise=function(){this.fields.hitCallbackTimeout=1E3;this.fields.maximumTagSize=2048;this.fields.maximumCookieSize=4096;this.fields.clientIdParam="_ijcid";this.fields.clientIdParamExpiry=3E5;this.fields.visibilityStateMonitor="never";this.fields.cookieName="SIVISITOR";this.fields.cookieExpires=31536E7;this.fields.deferCookieExpires=18E5;this.fields.clientTracking="full";this.fields.clientIdType="n";this.fields.clientIdPersistence="n";this.fields.location=decodeURIComponent(document.URL.replace(/\+/g,
" "));this.fields.title=document.title;this.fields.tz=(new Date).getTimezoneOffset();this.fields.language=navigator.language||navigator.userLanguage;this.fields.encoding=document.characterSet||document.charset;this.fields.screenColors=window.screen.colorDepth;this.documentId="js"+(new Date).getTime()+"r"+Math.round(1E3*Math.random())};g.prototype.require=function(){if(2==arguments.length&&d.isString(arguments[1])&&!this.modules[arguments[0]]){var a=this,b=arguments[0],c=arguments[1];a.modules[b]=
[];var e=document.createElement("script");e.async=!0;e.onload=function(){if(d.isFunction(f.moduleMap[b])){var c=a.modules[b];a.modules[b]=new f.moduleMap[b](a);for(var e=0;e<c.length;e++)f.apply(null,c[e])}};e.src=c;c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(e,c)}};g.prototype.setField=function(a,b){var c=!1;if(d.isString(a)&&!d.isEmpty(b)&&(a=a.trim(),b=d.isString(b)?b.trim():b,0<a.length))if("datamartId"==a){var e=d.getCollectionServer(b);e&&(this.fields[a]=b,this.fields.collectionServer=
e,c=!0)}else"name"==a?(e=this.fields.name,f.trackerMap[b]||(e?(this.fields[a]=b,f.trackerMap[b]=f.trackerMap[e],delete f.trackerMap[e]):this.fields[a]=b,c=!0)):"clientId"==a?d.isString(b)&&(this.setClientId(b),this.persistClientId(),c=!0):("clientTracking"==a&&""!==b?this.setPrivacy(b):this.fields[a]=b,c=!0);return c};g.prototype.set=function(){if(0<arguments.length){var a=arguments;d.isString(arguments[0])&&!d.isEmpty(arguments[1])&&(this.setField(arguments[0],arguments[1]),a=d.shiftArgs(a),a=d.shiftArgs(a));
var b=d.getFieldObject(a);if(b)for(var c in b)this.setField(c,b[c]);a=d.getCallBack(a);d.runCallback(a,this)}};g.prototype.get=function(a){return this.fields[a]};g.prototype.setClientId=function(a){if(a)return this.fields.clientId=a,this.fields.clientIdType="e",a;if(this.fields.clientId)return this.fields.clientId;a=d.getCookie(this.fields.cookieName);var b=this.getClientIdByQueryString();if(b)return this.fields.clientId=b,this.fields.clientIdType="m",a&&a!==b&&(this.fields.clientIdOverwritten=a),
this.fields.clientId;if(a)return this.fields.clientId=a,this.fields.clientIdType="o",this.fields.clientId;this.fields.clientId=d.makeClientId();this.fields.clientIdType="a";return this.fields.clientId};g.prototype.getClientIdByQueryString=function(){var a=this.fields.cookieQPName,b=f.getQP(this.fields.clientIdParam);if(b){var b=b.split("|"),c=(new Date).getTime();if(0<c-b[0]&&c-b[0]<this.fields.clientIdParamExpiry)return b[1]}return(a=f.getQP(a))?a:!1};g.prototype.persistClientId=function(){this.fields.clientIdType&&
this.fields.clientTracking&&("m"===this.fields.clientIdType||"a"===this.fields.clientIdType||"o"===this.fields.clientIdType?"none"===this.fields.clientTracking?(d.deleteCookie(this.fields.cookieName),this.fields.clientIdPersistence="n"):this.fields.clientIdPersistence=d.setCookie(this.fields.cookieName,this.fields.clientId,"full"==this.fields.clientTracking?this.fields.cookieExpires:0,this.fields.cookieDomain).cookieType:"e"===this.fields.clientIdType&&(d.deleteCookie(this.fields.cookieName),this.fields.clientIdPersistence=
"n"))};g.prototype.setPrivacy=function(a){this.fields.clientTracking=a;this.persistClientId();if("none"==a)ijDispatcher.processFlushDelDeferred(this.fields.name,!0,!0);else{a=ijDispatcher.tagSets;for(var b=0;b<a.length;b++)a[b]&&a[b].isPrivacyBlocked&&a[b].hit.tracker.fields.name==this.fields.name&&(a[b].isPrivacyBlocked=!1,"deferred"==a[b].hit.sendMethod?ijDispatcher.deferTagSet(a[b],!0):"immediate"==a[b].hit.sendMethod&&ijDispatcher.dispatchTagSet(a[b],!0))}};g.prototype.setCampaignData=function(){for(var a=
0;a<d.campaignParamList.length;a++){var b=f.getQP(d.campaignParamList[a]);b&&this.set(d.campaignDataList[a],b)}};g.prototype.addClientId=function(a){try{var b=this.fields.clientIdParam+"="+(new Date).getTime()+"|"+this.fields.clientId,c=new RegExp("([?&])"+this.fields.clientIdParam+"=\\d+\\|[^&$]+(&|$)");return c.test(a)?a.replace(c,"$1"+b+"$2"):a+(0<a.indexOf("?")?"&":"?")+b}catch(d){return a}};g.prototype.migrateClientId=function(a){try{if(a&&a.nodeName&&null!==this.fields.clientId)if("a"==a.nodeName.toLowerCase()||
"area"==a.nodeName.toLowerCase())a.href=this.addClientId(a.href);else if("form"==a.nodeName.toLowerCase())if("GET"==a.method.toUpperCase()){var b=null;if(a.elements)for(var c=0;c<a.elements.length&&!b;c++){var d=a.elements[c];d.name&&d.name==this.fields.clientIdParam&&(b=d)}b||(b=document.createElement("input"),b.setAttribute("name",this.fields.clientIdParam),b.setAttribute("type","hidden"),a.appendChild(b));b.setAttribute("value",(new Date).getTime()+"|"+this.fields.clientId)}else a.action=this.addClientId(a.action)}catch(h){}};
g.prototype.send=function(){try{this.doSend("immediate",arguments)}catch(a){}};g.prototype.sendDeferred=function(){try{this.doSend("deferred",arguments)}catch(a){}};g.prototype.processDeferred=function(a){try{"send"==a?ijDispatcher.flushDeferred(this.fields.name):a&&"clear"!=a||ijDispatcher.deleteDeferred(this.fields.name)}catch(b){}};g.prototype.doSend=function(a,b){if(0<b.length){this.persistClientId();var c=d.getCallBack(b),e=this.buildHit(b);e&&(e.sendMethod=a,ijDispatcher.dispatch(e));d.runCallback(c,
this)}};g.prototype.maxPayloadSize=function(){return 200>this.get("maximumTagSize")?200-this.get("collectionServer").length-69:this.get("maximumTagSize")-this.get("collectionServer").length-69};g.prototype.buildHit=function(a){var b=null,c=d.getFieldObject(a),e=null;d.isString(a[0])?(e=a[0],a=d.shiftArgs(a)):c.hitType&&(e=c.hitType);if(e){a=d.getArgParams(a);b=new x(e,this);b.tracker=this;if("pageview"==e||"screenview"==e)0<this.pageHitsSent&&(this.hits=0),this.pageHitsSent++;this.hits++;var h=c.hitCallback;
h&&(b.hitCallback=h);for(var h=this.maxPayloadSize(),f=new t,g=0;13>g;g++)for(var m="toycmwpraghij".charAt(g),k=this.getTagData(m,e,a,c),k=k&&!d.isString(k)?k.toString():k;k;)if(k=f.addToken(m,k,h))b.addPart(f),f=new t;b.addPart(f)}return b};g.prototype.getTagData=function(a,b,c,d){switch(a){case "t":return this.documentId+"."+(0<this.pageHitsSent?this.pageHitsSent:1);case "o":return this.hits;case "y":return b;case "c":return this.fields.clientId;case "m":return this.fields.clientIdOverwritten;case "w":return this.fields.clientIdType+
"."+this.fields.clientIdPersistence;case "p":return this.resolveField("location",null,d);case "r":return document.referrer;case "a":return this.resolveField("userId",null,d);case "g":return this.getClientData(d);case "h":return this.getCampaignData(d);case "i":return this.getContentData(b,c,d);case "j":return this.getOtherData(b,c,d);default:return null}};g.prototype.getContentData=function(a,b,c){var e={},e=this.getDataByType(a,"pageview",b,c,2,d.contentList);if(!d.isEmptyObject(e))return JSON.stringify(e)};
g.prototype.resolveField=function(a,b,c){return d.isEmpty(c[a])?d.isEmpty(b)?d.isEmpty(this.fields[a])?null:this.fields[a]:b:c[a]};g.prototype.getOtherData=function(a,b,c){var e={},e=d.mergeObjects(e,this.getEventData(a,b,c)),e=d.mergeObjects(e,this.getAppData(c)),e=d.mergeObjects(e,this.getExceptionData(a,b,c)),e=d.mergeObjects(e,this.getTimingData(a,b,c)),e=d.mergeObjects(e,this.getSocialData(a,b,c)),e=d.mergeObjects(e,this.getContentExperimentData(c));for(a=0;a<d.customFieldList.length;a++)e=d.mergeObjects(e,
this.getCustomVariableValue(d.customFieldList[a],c));if(!d.isEmptyObject(e))return JSON.stringify(e)};g.prototype.getEventData=function(a,b,c){return this.getDataByType(a,"event",b,c,4,d.eventList)};g.prototype.getDataByType=function(a,b,c,e,h,f){for(var g={},m=0;m<f.length;m++){var k="";h&&a==b&&0!==c.length&&m<h&&(k=c[m]);k=this.resolveField(f[m],k,e);k=d.isString(k)?k.trim():k;d.isEmpty(k)||(g[f[m]]=k)}return g};g.prototype.getCustomVariableValue=function(a,b){var c={},c=d.getFieldValueByPrefix(a,
this.fields,c);return c=d.getFieldValueByPrefix(a,b,c)};g.prototype.getAppData=function(a){return this.getDataByType(null,null,null,a,0,d.appFieldList)};g.prototype.getClientData=function(a){var b={},b=this.getDataByType(null,null,null,a,0,d.clientDataList);d.getPageVisibilityState()&&(b.visibility=d.getPageVisibilityState());b.screenResolution=window.screen.availWidth+"x"+window.screen.availHeight;if(!d.isEmptyObject(b))return JSON.stringify(b)};g.prototype.getCampaignData=function(a){var b={},b=
this.getDataByType(null,null,null,a,0,d.campaignDataList);if(!d.isEmptyObject(b))return JSON.stringify(b)};g.prototype.getExceptionData=function(a,b,c){return this.getDataByType(a,"exception",b,c,2,d.exceptionDataList)};g.prototype.getTimingData=function(a,b,c){return this.getDataByType(a,"timing",b,c,4,d.timingDataList)};g.prototype.getSocialData=function(a,b,c){return this.getDataByType(a,"social",b,c,3,d.socialDataList)};g.prototype.getContentExperimentData=function(a){return this.getDataByType(null,
null,null,a,0,d.contentExperimentDataList)};ijDispatcher=function(){};ijDispatcher.tagSets=[];ijDispatcher.dispatch=function(a){if(a){var b=this.buildTagSet(a);"none"==a.tracker.fields.clientTracking||"prerender"==d.getPageVisibilityState()?("none"==a.tracker.fields.clientTracking&&(b.isPrivacyBlocked=!0),"prerender"==d.getPageVisibilityState()&&(b.isPreRendering=!0),this.tagSets.push(b),d.runCallback(b.hit.hitCallback,b.hit.tracker),b.doneCallback=!0):"immediate"==a.sendMethod?this.dispatchTagSet(b):
"deferred"==a.sendMethod&&this.deferTagSet(b)}};ijDispatcher.buildTagSet=function(a){a=new y(a);this.buildURL(a);return a};ijDispatcher.buildURL=function(a){for(var b=a.hit,c=b.tracker.get("collectionServer")+"?",d=0;d<b.hitParts.length;d++){var h=d+1+"."+b.hitParts.length+"."+b.id,f="v="+b.v+"&i="+h+"&f="+b.hitParts[d].f+"&d="+b.hitParts[d].d+"&t="+(new Date).getTime();a.urls[d]=c+f;a.tagIds.push(h)}};ijDispatcher.dressURL=function(a){for(var b=0;b<a.urls.length;b++){var c=0,e=parseInt(d.extractPart("t",
a.urls[b],"&"),10);0<e&&(c=(new Date).getTime()-e,0>c&&(c=0));e=a.urls[b].indexOf("&t=");a.urls[b]=(0<=e?a.urls[b].substring(0,e):a.urls[b])+"&t="+c;a.urls[b]=a.urls[b]+"&c="+d.generateChecksum(a.urls[b].substring(1+a.urls[b].indexOf("?")))}};ijDispatcher.dispatchTagSet=function(a,b){this.dressURL(a);for(var c=0;c<a.urls.length;c++){var e=new Image;e.src=a.urls[c];a.images.push(e)}a.imagesComplete=0;a.isRequested=!0;b||this.tagSets.push(a);for(var h=a.hit?a.hit.tracker:null,f=a.hit?a.hit.hitCallback:
null,g=a.images,c=function(){a.imagesComplete++;a.imagesComplete==g.length&&(a.isComplete=!0,f&&!a.doneCallback&&(a.doneCallback=!0,d.runCallback(f,h)))},e=0;e<a.images.length;e++)a.images[e].onload=c,a.images[e].onerror=c;h&&f&&setTimeout(function(){a.didTimeout=!0;f&&!a.doneCallback&&(a.doneCallback=!0,d.runCallback(f,h))},h.fields.hitCallbackTimeout)};ijDispatcher.deferTagSet=function(a,b){if(a&&0<a.urls.length){for(var c=a.hit.id.length+2,e=0;e<a.urls.length;e++)c+=a.urls[e].length+2;document.cookie.length+
c>a.hit.tracker.fields.maximumCookieSize?this.dispatchTagSet(a):(a.isDeferred=!0,a.cookie=d.setCookie("iJ."+a.hit.id,a.urls.toString().replace(/,/g,"|"),"full"==a.hit.tracker.fields.clientTracking?a.hit.tracker.fields.deferCookieExpires:0,a.hit.tracker.fields.cookieDomain).cookieDetails,b||this.tagSets.push(a),a.hit.hitCallback&&!a.doneCallback&&d.runCallback(a.hit.hitCallback,a.hit.tracker),a.doneCallback=!0)}};ijDispatcher.flushDeferred=function(a){ijDispatcher.processFlushDelDeferred(a)};ijDispatcher.deleteDeferred=
function(a){ijDispatcher.processFlushDelDeferred(a,!0)};ijDispatcher.processFlushDelDeferred=function(a,b,c){for(var e=this.tagSets,f=0;f<e.length;f++)e[f]&&e[f].isDeferred&&e[f].hit.tracker.fields.name==a&&((e[f].doneCallback=!1,d.deleteCookie("iJ."+e[f].hit.id),b&&!c)?delete e[f]:b||c?b&&c&&(e[f].isPrivacyBlocked=!0):this.dispatchTagSet(e[f],!0))};ijDispatcher.sendDeferredTags=function(){for(var a=this.loadDeferredTagSets(),b=0;b<a.length;b++)this.dispatchTagSet(a[b])};ijDispatcher.loadDeferredTagSets=
function(){var a=[];if(document.cookie)for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var e=b[c].match("^ *iJ\\.(\\d+\\.\\d+\\.[+-]?\\w+)=(.+)$");if(e&&3==e.length){var f=new y(null);f.cookie="iJ."+e[1];f.urls=e[2].split("|");for(var g=0;g<f.urls.length;g++)f.tagIds.push(g+1+"."+f.urls.length+"."+e[1]);d.deleteCookie(f.cookie);a.push(f)}}return a};"object"!==typeof JSON&&(JSON={});"function"!==typeof JSON.stringify&&(s=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
w={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,b,c){var e;r=n="";if("number"===typeof c)for(e=0;e<c;e+=1)r+=" ";else"string"===typeof c&&(r=c);if((p=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return d.str("",{"":a})});"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});ijDispatcher.sendDeferredTags();d.bindVisibilityStateChanger();
var z=q.iJentoTagObject,u=q[z].q;q[z]=f;for(q=0;u&&q<u.length;q++)f.apply(null,u[q])})(window);
